# Generated by Django 4.2.21 on 2025-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quanity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
