# Generated by Django 4.2.21 on 2025-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_anticipation', 'В ожидании'), ('ready', 'Готово'), ('rejected', 'Отклонено')], default='in_anticipation', max_length=20),
        ),
    ]
