# Generated by Django 4.2.21 on 2025-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_name_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
