# Generated by Django 4.2 on 2025-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
